-- Account Information and Basic Metadata
-- This query extracts basic account information from Snowflake's ACCOUNT_USAGE schema

SELECT 
    CURRENT_ACCOUNT() as ACCOUNT_NAME,
    CURRENT_REGION() as REGION,
    CURRENT_VERSION() as SNOWFLAKE_VERSION,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP,
    'account_info' as EXTRACT_TYPE
FROM (SELECT 1) -- Dummy table for single row result
UNION ALL
SELECT 
    'DATABASES' as ACCOUNT_NAME,
    COUNT(*)::VARCHAR as REGION,
    NULL as SNOWFLAKE_VERSION,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP,
    'database_count' as EXTRACT_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES
WHERE DELETED IS NULL
UNION ALL
SELECT 
    'WAREHOUSES' as ACCOUNT_NAME,
    COUNT(*)::VARCHAR as REGION,
    NULL as SNOWFLAKE_VERSION,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP,
    'warehouse_count' as EXTRACT_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSES
WHERE DELETED IS NULL
UNION ALL
SELECT 
    'USERS' as ACCOUNT_NAME,
    COUNT(*)::VARCHAR as REGION,
    NULL as SNOWFLAKE_VERSION,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP,
    'user_count' as EXTRACT_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
WHERE DELETED_ON IS NULL;