-- Database and Schema Information
-- Extract database, schema, table, and view metadata

SELECT 
    DATABASE_NAME,
    DATABASE_OWNER,
    IS_TRANSIENT,
    CREATED,
    LAST_ALTERED,
    DELETED,
    COMMENT,
    'DATABASE' as OBJECT_TYPE,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASES
WHERE DELETED IS NULL
    AND DATABASE_NAME NOT IN ('SNOWFLAKE', 'UTIL_DB')

UNION ALL

SELECT 
    CATALOG_NAME as DATABASE_NAME,
    SCHEMA_OWNER as DATABASE_OWNER,
    IS_TRANSIENT::BOOLEAN as IS_TRANSIENT,
    CREATED,
    LAST_ALTERED,
    DELETED,
    COMMENT,
    'SCHEMA' as OBJECT_TYPE,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.SCHEMATA
WHERE DELETED IS NULL
    AND CATALOG_NAME NOT IN ('SNOWFLAKE', 'UTIL_DB')
    AND SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA')

UNION ALL

SELECT 
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_OWNER as DATABASE_OWNER,
    IS_TRANSIENT::BOOLEAN as IS_TRANSIENT,
    CREATED,
    LAST_ALTERED,
    DELETED,
    COMMENT,
    CONCAT(TABLE_TYPE, '_TABLE') as OBJECT_TYPE,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE DELETED IS NULL
    AND TABLE_CATALOG NOT IN ('SNOWFLAKE', 'UTIL_DB')
    AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')

UNION ALL

SELECT 
    TABLE_CATALOG as DATABASE_NAME,
    TABLE_OWNER as DATABASE_OWNER,
    IS_SECURE::BOOLEAN as IS_TRANSIENT,
    CREATED,
    LAST_ALTERED,
    DELETED,
    COMMENT,
    'VIEW' as OBJECT_TYPE,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.VIEWS
WHERE DELETED IS NULL
    AND TABLE_CATALOG NOT IN ('SNOWFLAKE', 'UTIL_DB')
    AND TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA');