-- Query History and Performance Analysis
-- Extract query execution patterns, performance metrics, and user activity

SELECT 
    QUERY_ID,
    QUERY_TYPE,
    DATABASE_NAME,
    SCHEMA_NAME,
    USER_NAME,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME,
    EXECUTION_TIME,
    COMPILATION_TIME,
    QUEUED_PROVISIONING_TIME,
    QUEUED_REPAIR_TIME,
    QUEUED_OVERLOAD_TIME,
    TRANSACTION_BLOCKED_TIME,
    BYTES_SCANNED,
    BYTES_WRITTEN,
    BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE,
    ROWS_PRODUCED,
    CREDITS_USED_CLOUD_SERVICES,
    ERROR_CODE,
    ERROR_MESSAGE,
    DATE(START_TIME) as QUERY_DATE,
    HOUR(START_TIME) as QUERY_HOUR,
    EXTRACT(dayofweek FROM START_TIME) as DAY_OF_WEEK,
    CASE 
        WHEN TOTAL_ELAPSED_TIME >= 300000 THEN 'LONG_RUNNING'
        WHEN TOTAL_ELAPSED_TIME >= 60000 THEN 'MEDIUM'
        ELSE 'SHORT'
    END as QUERY_DURATION_CATEGORY,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -{lookback_days}, CURRENT_TIMESTAMP())
    AND QUERY_TYPE IS NOT NULL
    AND USER_NAME IS NOT NULL
    AND WAREHOUSE_NAME IS NOT NULL
ORDER BY START_TIME DESC;

-- Note: {lookback_days} will be replaced with the configured lookback period