-- Storage Usage and Cost Analysis
-- Extract storage utilization and cost metrics

SELECT 
    DATABASE_NAME,
    USAGE_DATE,
    STORAGE_BYTES,
    STAGE_BYTES,
    FAILSAFE_BYTES,
    HYBRID_TABLE_STORAGE_BYTES,
    STORAGE_BYTES / (1024*1024*1024) as STORAGE_GB,
    STAGE_BYTES / (1024*1024*1024) as STAGE_GB,
    FAILSAFE_BYTES / (1024*1024*1024) as FAILSAFE_GB,
    HYBRID_TABLE_STORAGE_BYTES / (1024*1024*1024) as HYBRID_TABLE_GB,
    EXTRACT(dayofweek FROM USAGE_DATE) as DAY_OF_WEEK,
    EXTRACT(month FROM USAGE_DATE) as USAGE_MONTH,
    EXTRACT(year FROM USAGE_DATE) as USAGE_YEAR,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE >= DATEADD('day', -{lookback_days}, CURRENT_DATE())
    AND DATABASE_NAME NOT IN ('SNOWFLAKE', 'UTIL_DB')
ORDER BY USAGE_DATE DESC, DATABASE_NAME;

-- Note: {lookback_days} will be replaced with the configured lookback period