-- User Activity and Access Patterns
-- Extract user activity, login patterns, and access history

SELECT 
    USER_NAME,
    CLIENT_IP,
    REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION,
    FIRST_AUTHENTICATION_FACTOR,
    SECOND_AUTHENTICATION_FACTOR,
    IS_SUCCESS,
    ERROR_CODE,
    ERROR_MESSAGE,
    EVENT_TIMESTAMP,
    DATE(EVENT_TIMESTAMP) as LOGIN_DATE,
    HOUR(EVENT_TIMESTAMP) as LOGIN_HOUR,
    EXTRACT(dayofweek FROM EVENT_TIMESTAMP) as DAY_OF_WEEK,
    CURRENT_TIMESTAMP() as EXTRACT_TIMESTAMP
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('day', -{lookback_days}, CURRENT_TIMESTAMP())
    AND USER_NAME IS NOT NULL
ORDER BY EVENT_TIMESTAMP DESC;

-- Note: {lookback_days} will be replaced with the configured lookback period