name: redshift_assessment_serverless
version: "1.0"
extract_folder: "/tmp/data/redshift_assessment/serverless"
steps:
  - name: query_view
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/0_query_view.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: rs_spectrum_tb_month
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/1_rs_spectrum_tb_month.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: rs_managed_storage_gb
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/2_rs_managed_storage_gb.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: rs_nodes
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/3_rs_nodes.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: rs_avg_concurrent_users
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/4_rs_avg_concurrent_users.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: rs_avg_queries_minute
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/5_rs_avg_queries_minute.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: chart_query_type_by_hour
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/6_chart_query_type_by_hour.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: chart_cpu_consumption_by_query_type
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/7_chart_cpu_consumption_by_query_type.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: chart_concurrent_users_by_hour
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/8_chart_concurrent_users_by_hour.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: chart_cpu_consumption_by_hour_and_query_type
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/9_chart_cpu_consumption_by_hour_and_query_type.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: cost_incurred
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/redshift/serverless/10_cost_incurred.sql
    mode: overwrite
    frequency: once
    flag: active
