name: oracle_assessment
version: "1.0"
extract_folder: "/tmp/data/oracle_assessment"
steps:
  - name: config_containers
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_containers.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: config_db_features
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_db_features.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: config_instance
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_instance.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: config_memory_evolution
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_memory_evolution.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: config_pdb_objects
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_pdb_objects.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: config_pdb_partitions
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_pdb_partitions.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: config_storage
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/config_storage.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: perf_cpu_waits
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/perf_cpu_waits.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: perf_fgd_session_evolution
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/perf_fgd_session_evolution.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: perf_heatmap
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/perf_heatmap.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: perf_heatmap_raw
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/perf_heatmap_raw.sql
    mode: overwrite
    frequency: once
    flag: inactive
  - name: perf_sqltext
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/perf_sqltext.sql
    mode: overwrite
    frequency: once
    flag: active
  - name: test_nulloutput
    type: sql
    extract_source: src/databricks/labs/lakebridge/resources/assessments/oracle/test_nulloutput.sql
    mode: overwrite
    frequency: once
    flag: active
